# Generated by Django 2.0 on 2018-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='nongdu',
            field=models.FloatField(max_length=30),
        ),
    ]
