# Generated by Django 2.0 on 2018-05-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180519_2122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='dust_monitor',
        ),
    ]
